### ISSUE TITLE
Manually create pages

### ISSUE THREAD

**Issue by synox** [hlxsites/24life#105]
See <https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/24life/drafts/import-status.xlsx?d=w5bb100872c464deda9e2a42bd882ac6e&csf=1&web=1&e=9etZCF> and filter by `Type=Page`

e.g. 
https://www.24life.com/about-us/history-of-24-hour-fitness/
https://www.24life.com/about-us/
https://www.24life.com/happy-hour-mobile/

**Comment by iamitshri** [comment]
@synox only /happy-hour-mobile is pending regarding this issue.   created  #148  for that. Closing this one after some more validation.
