### ISSUE TITLE
Magazine form implementation pointing to "https://www.createsend.com/t/subscribeerror?description="

### ISSUE THREAD

**Issue by meejain** [hlxsites/24life#110]
For Eg - https://www.24life.com/magazine/volume-6-issue-2/

**Comment by meejain** [comment]
Checking with the Customer - 

Similarly for this form as well in the magazine URL - https://www.24life.com/magazine/volume-6-issue-2/
Here also we see id="subForm" - action="https://www.createsend.com/t/subscribeerror?description="
[Createsend.com](http://createsend.com/) collects, stores, and manages information on Your behalf, as directed by You. Seems like here also some kind of integration is done with [createsend.com](http://createsend.com/).
Are their integration steps / code that you may share with us so that we may further materialize the same integration via Franklin ?

**Comment by synox** [comment]
customer: 
> we may want to eliminate the newsletter all together for this release.
