### ISSUE TITLE
LHS: improve article view

### ISSUE THREAD

**Issue by synox** [hlxsites/24life#133]
https://main--24life--hlxsites.hlx.page/fitness/2021/jennifer-finds-the-power-to-persevere

- It briefly shows block data instead of hiding it
![Screen Recording 2023-09-08 at 09 24 23](https://github.com/hlxsites/24life/assets/2250964/5c7b3e6f-e951-4bbb-9082-997220f093a8)

- Performance score is bad on mobile and desktop: https://pagespeed.web.dev/analysis/https-main--24life--hlxsites-hlx-page-fitness-2021-jennifer-finds-the-power-to-persevere/42gfoex9d4?form_factor=mobile
<img width="1001" alt="Screenshot 2023-09-08 at 09 26 19" src="https://github.com/hlxsites/24life/assets/2250964/401c6da5-85f6-4930-bf20-706663e69fa6">

**Comment by synox** [comment]
score is still now

**Comment by rrusher** [comment]
@synox 
<img width="1018" alt="Screenshot 2023-09-22 at 1 36 09 PM" src="https://github.com/hlxsites/24life/assets/6796243/c191a75f-cdde-407f-a536-a51d180c04e8">

Mobile LHS could still use some work, but it's showing the font as the major contributing factor.

**Comment by rrusher** [comment]
Actually, here's mobile.
<img width="1034" alt="Screenshot 2023-09-22 at 1 45 36 PM" src="https://github.com/hlxsites/24life/assets/6796243/0a9a43d9-e92e-433f-b985-9b1988ebd21c">

**Comment by synox** [comment]
wohooo 👍
