### ISSUE TITLE
LHS: reduce layout shift

### ISSUE THREAD

**Issue by synox** [hlxsites/24life#149]
There is layout shift in the navigation and on the search result page, preventing the LHS to be 100. 

https://main--24life--hlxsites.hlx.live/
https://main--24life--hlxsites.hlx.live/search?q=san%20francisco

Observations: 
 - The logo in the nav seems to push the content
 - The cards first render without the image, and then get pushed down by the image. We can set a fixed height for the image. 

Tips: use Google Chrome to run the Lighthouse report. Then press "View Original Trace" to see each frame of the rendering. 

https://web.dev/optimize-cls/

![Screen Recording 2023-09-13 at 11 09 07](https://github.com/hlxsites/24life/assets/2250964/ac95dd1a-e04d-4cce-b3fb-33537f6a9be0)

**Comment by meejain** [comment]
This is taken care via - https://github.com/hlxsites/24life/pull/159
