### ISSUE TITLE
Colorful headers in about-us

### ISSUE THREAD

**Issue by synox** [hlxsites/24life#15]
https://www.24life.com/about-us/

We can have a section for each header, and set the `style` metadata property to override the h3 color. 

![Screenshot 2023-07-31 at 11 11 33](https://github.com/hlxsites/24life/assets/2250964/1abd5de5-44ff-482f-a4e7-a66e58e219be)

**Comment by dirudeen** [comment]
Hello! I'm new to open source projects and I will appreciate it if you could let me contribute to your project?
