### ISSUE TITLE
Magazine: <BR STYLE="BACKGROUND-IMAGE: NONE;">

### ISSUE THREAD

**Issue by synox** [hlxsites/24life#191]
https://main--24life--hlxsites.hlx.page/magazine/volume-4-issue-7

Also verify other magazine issues. 

![Screenshot 2023-09-26 at 10 08 23](https://github.com/hlxsites/24life/assets/2250964/f3403860-5d9e-4246-b44f-372af9cb3a92)

**Comment by rrusher** [comment]
I searched the doc repo for other possible instances of this error. A few others found and replaced.
