### ISSUE TITLE
Collection Hero

### ISSUE THREAD

**Issue by synox** [hlxsites/24life#23]
There are currently 14 collections. 

https://www.24life.com/collections/feel-better/
https://www.24life.com/collections/success-stories/

![Screenshot 2023-07-31 at 11 36 45](https://github.com/hlxsites/24life/assets/2250964/d8878e65-a4a1-41ba-b7ad-ebc1b015bc41)

See https://www.24life.com/page-sitemap.xml

**Comment by iamitshri** [comment]
Artlcle list block was updated to show collections in this RP https://github.com/hlxsites/24life/pull/76 
Collection Hero block is created

**Comment by synox** [comment]
@iamitshri please also create the content documents as part of this issue.

**Comment by iamitshri** [comment]
@synox yes on my list. I saw your slack after closing this..

**Comment by iamitshri** [comment]
https://main--24life--hlxsites.hlx.page/collections/corporate-wellness
https://main--24life--hlxsites.hlx.page/collections/feel-better
https://main--24life--hlxsites.hlx.page/collections/get-lean
https://main--24life--hlxsites.hlx.page/collections/get-started
https://main--24life--hlxsites.hlx.page/collections/get-strong
https://main--24life--hlxsites.hlx.page/collections/mental-hacks
https://main--24life--hlxsites.hlx.page/collections/recipes
https://main--24life--hlxsites.hlx.page/collections/running
https://main--24life--hlxsites.hlx.page/collections/sleep
https://main--24life--hlxsites.hlx.page/collections/success-stories
https://main--24life--hlxsites.hlx.page/collections/videos
https://main--24life--hlxsites.hlx.page/collections/workouts
https://main--24life--hlxsites.hlx.page/collections/yoga
