### ISSUE TITLE
Magazine: Next button

### ISSUE THREAD

**Issue by synox** [hlxsites/24life#29]
https://www.24life.com/graphic-designer-by-day-this-gx24-instructor-says-power-jumping-with-you-is-worth-it/

TODO: clarify: is this specified in a metadata, added as link in the document, or pulled from a JSON table? 

![Screenshot 2023-07-31 at 11 48 46](https://github.com/hlxsites/24life/assets/2250964/643856d2-7776-4674-a1a4-9469454bc3b3)

**Comment by rrusher** [comment]
@synox I think this should be part of the magazine block.

Since each magazine issue is essentially a list of articles, the block should have a `next` property with the URL for the next article.

**Comment by synox** [comment]
@rrusher I think this should just be a standard link, maybe a different background and border color when in the context of an article. This gives the authors more freedom.
