### ISSUE TITLE
Add redirects for urls ending with a slash

### ISSUE THREAD

**Issue by synox** [hlxsites/24life#38]
# Background
The original site has trailing slashes for each url. e.g. https://www.24life.com/isabel-beats-incredible-odds/

If mapped directly in Franklin, this would be `isabel-beats-incredible-odds/index.docx`. Having thousands of `index.docx` files is difficult to manage (e.g. Sharepoint search shows just the filename, index.docx for each result. 

Therefore we are creating documents by it's name, e.g. 
- document: /isabel-beats-incredible-odds.docx
- franklin url: https://www.24life.com/isabel-beats-incredible-odds

# Task
This can be achieved either by a CDN rewrite/redirect rule, or adding a list of urls to the redirect spread sheet. 

Note: so far we assume there is no CDN.

**Comment by rrusher** [comment]
Created a redirects.xlsx.
I'll add all the URLs from the import list to this sheet.

**Comment by rrusher** [comment]
All urls added from import.
